version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{.Branch}}"

builds:
  - id: "aerospike-backup"
    main: cmd/backup/main.go
    binary: "aerospike-backup"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'main.appVersion={{.Version}}' -X 'main.commitHash={{.Commit}}' -X 'main.buildTime={{.Date}}'
  - id: "aerospike-restore"
    main: cmd/restore/main.go
    binary: "aerospike-restore"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'main.appVersion={{.Version}}' -X 'main.commitHash={{.Commit}}' -X 'main.buildTime={{.Date}}'

archives:
  - id: "aerospike-backup"
    formats:  [ 'tar.gz' ]
    name_template: >-
      {{ .Binary }}-{{ .Version }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
    ids:
      - "aerospike-backup"
  - id: "aerospike-restore"
    formats:  [ 'tar.gz' ]
    name_template: >-
      {{ .Binary }}-{{ .Version }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE
    ids:
      - "aerospike-restore"

release:
  prerelease: true
  make_latest: false
  replace_existing_artifacts: true
  mode: prepend
  header: |
    ## Release {{ .Version }} ({{ .Date }})
    - aerospike-backup (CLI tool)
    - aerospike-restore (CLI tool)
    - backup-go (library)

changelog:
  disable: true

checksum:
  name_template: "{{ .ArtifactName }}.sha256"
  split: true
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: gpg
    args:
      - --batch
      - --armor
      - --yes
      - -u
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${artifact}.asc"
      - --detach-sign
      - "${artifact}"
    signature: "${artifact}.asc"
    env:
      - GPG_FINGERPRINT
